### ISSUE TITLE
Problems with the time input

### ISSUE THREAD

**Issue by asraelvudogel** [jheubuch/traewelling-android#194]
**Description**

If I want to log into a connection and display the departures of the station, then it can happen that at large stations not all trains of the next quarter of an hour are displayed, because there are simply too many. The filters according to the traffic types do not help either. If I then press the buttons next jump the app but always immediately 15 min ahead.
So I have to manually enter my departure time. Also, the app recently jumps to 00:00 clock and you always have to awkwardly select the current time again. That was different before.

Wenn ich mich in eine Verbindung einloggen will und mit die Abfahrten der Station anzeigen lassen, dann kann es sein, dass bei großen Bahnhöfen nicht alle Züge der nächsten Viertelstunde angezeigt werden, weil es einfach zu viele sind. Da helfen auch nicht die Filter nach den Verkehrsarten. Wenn ich dann die Buttons nächster betätige spring die App aber immer gleich 15 min vor.
So muss ich also händisch meine Abfahrtszeit eingeben. Auch dabei spingt die App neuerdings auf 00:00 Uhr und man muss die aktuelle Uhrzeit immer umständlich erst wieder auswählen. Das war auch schon mal anders.

**Expected behavior**
Really show all connections in the next quarter of an hour. Improvement of the time input, that always the current time is already preset.

Wirklich alle Verbindungen der nächsten Viertelstunde anzeigen. Verbesserung der Zeiteingabe, dass immer die aktuelle Zeit bereits voreingestellt ist.

**Smartphone:**
 - Device: Oneplus 6
 - OS: Android 12
 - Appversion: 1.19.0 (100)

**Comment by jheubuch** [comment]
Hi,
this will be fixed in the next release.

This happens if too much (>30) departures at a station are happening in 15mins. The the last few are purged by HAFAS.
I now have re-implemented the filter-system so that the trips are re-loaded when a filter is selected. And then only the filtered connections are transmitted via the interface and hopefully all trips could be shown that way.

Furthermore I improved the time picker so that the current search time is pre-selected.
