### ISSUE TITLE
Checkin to last stop not possible if the train terminates earlier than normal

### ISSUE THREAD

**Issue by dasBunny** [jheubuch/traewelling-android#40]
**Describe the bug**
When checking in to a train that has its last stop(s) cancelled, the stop where the train now terminates is listed as cancelled, even though it is still possible to go to that station. 

**To Reproduce**
Try to check in to any connection that has its last stop cancelled. 

**Expected behavior**
The arrival time of the new terminus station is listed and I can check in to that station.

**Comment by DRSchlaubi** [comment]
I took a look at the API response, and it looks like Träwelling/DBRest actually marks the last stop as cancelled.

I will investigate this further to check whether this is always the case

The träwelling website has a similar problem, where the "last stop" button is off-by-one and chooses Raunheim rather than Rüsselsheim
![image](https://user-images.githubusercontent.com/16060205/194751891-b1daced8-e690-41f0-8551-76e70c27d97a.png)
