### ISSUE TITLE
DB Ticket

### ISSUE THREAD

**Issue by chukfinley** [jheubuch/traewelling-android#449]
![screenshot](https://github.com/user-attachments/assets/e6b74ad3-33ff-4239-b768-278ac624af87)
In the Screenshot from F-droid there is this D-Ticket button with the qr code logo is that for the Deutschland Ticket if yes how do I add it?

**Comment by jheubuch** [comment]
Hi,
with this feature you can tag your journeys with stuff like
- ticket you used
- train class
- travel class
- seat
- ...

Träwelldroid can not(!) display your Deutschland-Ticket.

P.S. since this was a question and not a feature request/bug report, please use the preferred communication way via Mastodon/E-Mail in future. Thank you :)
