### ISSUE TITLE
Missing line icon RB 73 in Schleswig-Holstein

### ISSUE THREAD

**Issue by gordon-fr33man** [jheubuch/traewelling-android#462]
### Is there an existing issue for your request?

- [X] I have searched the existing issues and did not find an open one

### Is your issue regarding to timetable or routing data within any check-in displayed in
Träwelldroid?

- [X] I have no issue with the displayed timetable or check-in data.

### Describe the bug / current behaviour

Whenever you call up the line RB 73 from Kiel to Rieseby Schleibrücke-Süd (NAH.SH), the line icon is missing. The color and shape are correctly stored in the line-colors.csv file in traewelling's Github repository (as far as I can tell). The problem does not exist with the sister line RE 72 or other lines in NAH.SH area like RE 7 or RB 82.

### Describe the expected behaviour

I expect the line icons to be displayed equally for all lines.

### Your app version

v2.17.2 (179)

### Anything else?

I have just updated the line icons in the settings.

**Comment by jheubuch** [comment]
Hi.

Following entry is included in the line-colors.csv

![Screenshot_20241222-085720.png](https://github.com/user-attachments/assets/3dfcbfa0-054d-4d86-94a5-f0844a1d81c3)

The line id in the csv file is `nbe-re73` but HAFAS has the line id `nbe-rb73`

Since the data in the CSV is wrong, Träwelldroid is not showing the icon.
